Iter5
dlc-01/http-metric-serv-go pull request #6
Opened 2023-04-11 19:14 UTC by dlc-01

2023-04-14 16:35 UTC, mshogin requested changes
Очень здорово! Код понятный, идея ясна. Реализация достаточно компактная.
Остались некоторые моменты для улучшения.

2023-04-14 16:35 UTC, mshogin commented on cmd/agent/main.go
> +			panic(err)
предлагаю не кидать панику а возвращать ошибку
```
return fmt.Errorf("cannot parse REPORT_INTERVAL: %w", err)
```

все паники ниже тоже самое

2023-04-14 16:35 UTC, mshogin commented on cmd/agent/main.go
> +	metrics := new(metrics.MemMetrics)
предлагаю в пакете metrics сделать 
1. функцию Init на уровне пакета
2. функция будет возвращать *metrics.MemMetrics
3. (рекомендация) переименовать MemMetrics -> MemStorage
4. не называть переменные по имени пакета metrics это и имя пакета и имя переменной  - ведет к путанице

тогда получится 
```
m := metrics.Init()
```

2023-04-14 16:35 UTC, mshogin commented on cmd/agent/main.go
> +		if timeCounter == int(reportInterval/pollInterval) {
critical: это условие выполнится один раз
необходимо обнулить timeCounter если условие сработало

для решения задач с выполнением периодических действий существует стандартный шаблон
```
	term := make(chan os.Signal, 1)
	signal.Notify(term, syscall.SIGINT, syscall.SIGTERM)
	t1 := time.NewTicker(time.Second * 5)
	t2 := time.NewTicker(time.Second * 2)
	running := true
	for running {
		select {
		case <-t1.C:
			fmt.Printf("%+v\n", "every 5 sec") // output for debug
		case <-t2.C:
			fmt.Printf("%+v\n", "every 2 sec") // output for debug
		case <-term:
			fmt.Printf("%+v\n", "termination") // output for debug
			running = false
		}
	}
```
предлагаю его адаптировать для решения этой задачи

2023-04-14 16:35 UTC, mshogin commented on cmd/server/main.go
> +	storage.Ms.Init()
предлагаю спрятать детали имплементации и должно получится
```
storage.Init()
```

2023-04-14 16:35 UTC, mshogin commented on cmd/server/main.go
> +	fmt.Println("Server address:" + serverAddress)
это можно удалить, gin выдает всю информацию при старте

2023-04-14 16:35 UTC, mshogin commented on cmd/server/main.go
> +	router.POST("/update/:types/*name", handlers.UpdateHandler)
предлагаю
заменить POST на
```
	router.POST("/update/:types/:name/:value", handlers.UpdateHandler)
```

далее в UpdateHandlers.go использовать эти параметры
```
	types := gin.Param("types")
	key := gin.Param("name")
	value := gin.Param("value")
```

и соответственно удалить все что связано с
```
	keyValue := gin.Param("name")
	url := strings.Split(keyValue, "/")

```

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/UpdateHandlers.go
> +		gin.String(http.StatusNotImplemented, "Not a supported metric.")
предлагаю заменить сообщение на 
```
Unsupported metric type
```

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/UpdateHandlers.go
> +		storage.Ms.SetGauge(key, value)
предлагаю спрятать детали реализации 
```
storage.SetGauge(...)
```

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/UpdateHandlers.go
> +		storage.Ms.SetCounter(key, value)
предлагаю спрятать детали реализации 
```
storage.SetCounter(...)
```

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/UpdateHandlers.go
> +		value, _ = storage.Ms.GetCounter(key)
предлагаю удалить этот код: у нас уже есть key and value

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/UpdateHandlers.go
> +		value, _ = storage.Ms.GetGauge(key)
предлагаю удалить этот код: у нас уже есть key and value

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/ValueHandler.go
> +			gin.String(http.StatusNotFound, "Not a supported metric.")
предлагаю заменить сообщение на 
```
fmt.Sprintf("Counter %q not found", key)
```

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/ValueHandler.go
> +			gin.String(http.StatusNotFound, "Not a supported metric.")
предлагаю заменить сообщение на 
```
fmt.Sprintf("Gauge %q not found", key)
```

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/ValueHandler.go
> +		value, exist := storage.Ms.GetCounter(key)
предлагаю спрятать детали реализации
```
v, ok := storage.GetCounter(...)
```

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/ValueHandler.go
> +		value, exist := storage.Ms.GetGauge(key)
предлагаю спрятать детали реализации
```
v, ok := storage.GetGauge(...)
```

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/ValueHandler.go
> +		gin.String(http.StatusNotFound, "Not a supported metric.")
Not a supported metric.
v
Unsupported metric type

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/ValueHandler.go
> +package handlers
предлагаю вынести "counter" and "gauge" в 
```
const (
      GaugeTypeName = "gauge"
      CounterTypeName = "counter"
)
```
и использовать их в коде

2023-04-14 16:35 UTC, mshogin commented on internal/server/storage/MemStorage.go
> +	(*Ms).gauges = make(map[string]float64)
достаточно
```
	Ms.gauges = make(map[string]float64)
	Ms.counters = make(map[string]int64)
```

2023-04-14 16:35 UTC, mshogin commented on internal/server/storage/MemStorage.go
> +func (Ms *MemStorage) SetGauge(k string, v float64) {
```
func (ms *MemStorage) SetGauge
```
более go-way

2023-04-14 16:35 UTC, mshogin commented on internal/agent/metrics/RuntimeMetrics.go
> +package metrics
рекомендация: предлагаю все файлы именовать с маленькой буквы
runtime_metrics.go 
это общепринятый подход

2023-04-14 16:35 UTC, mshogin commented on cmd/server/main_test.go
> +package main
for information only (no actions are required)

достаточно редко пишут тесты на main
если на main есть тест это говорит о том что в main присутствует бизнес логика которой быть недолжно. В данном случае это своего рода acceptance тест. Очень класно всегда иметь такой тест, он позволяет достаточно просто проверять что наше приложение делает свою работу.

Часто такие тесты держат в папке tests, которая располагается в корне проекта. В нашем случае если переносить тест в папку tests, это повлечет за сосбой некоторую переработку кодовой базы.

Предлагаю сначала довести работу до приемки, а потом если у тебя будет время рекомендую попробовать перенести тест в tests.

2023-04-14 16:35 UTC, mshogin commented on cmd/server/main_test.go
> +func TestInitRouter(t *testing.T) {
предлагаю привести тест к виду AAA (Arrange, Act, Assert)

```
	// Arrange
	router := setupRouter()
	storage.Ms.Init()
	wPost := httptest.NewRecorder()
	wGet := httptest.NewRecorder()

	// Act
	reqPost, _ := http.NewRequest(http.MethodPost, "/update/gauge/test/666", nil)
	router.ServeHTTP(wPost, reqPost)
	reqGet, _ := http.NewRequest(http.MethodGet, "/value/gauge/test", nil)
	router.ServeHTTP(wGet, reqGet)

	// Assert
	assert.Equal(t, 200, wPost.Code)
	assert.Equal(t, "666", wGet.Body.String())
```

2023-04-14 16:35 UTC, mshogin commented on internal/agent/metrics/RuntimeMetrics_test.go
> +			fields: fields{gauge: map[string]float64{
форматирование
```
		{
			name: "firstTest",
			fields: fields{
				gauge: map[string]float64{
					"Alloc": 5.454,
					"Da":    5.7,
				},
				counter: map[string]int64{
					"first":  1,
					"second": 2,
				},
			},
		},
```
так более читабельно

2023-04-14 16:35 UTC, mshogin commented on internal/agent/metrics/RuntimeMetrics_test.go
> +			metrics.Check()
не понятно что проверяем

2023-04-14 16:35 UTC, mshogin commented on internal/agent/metrics/RuntimeMetrics_test.go
> +func TestMemMetrics_Init(t *testing.T) {
тут ничего не тестируем - просто удалить

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/UpdateHandlers.go
> +func UpdateHandler(gin *gin.Context) {
предлагаю написать тест

2023-04-14 16:35 UTC, mshogin commented on internal/server/handlers/ValueHandler.go
> +func ValueHandler(gin *gin.Context) {
предлагаю написать тест

2023-04-14 18:47 UTC, dlc-01 commented on cmd/server/main.go
> +	router.POST("/update/:types/*name", handlers.UpdateHandler)
а если так сделать он будет выдавать  307 Temporary Redirect, когда нужно 500. Тесты не будет проходит. Я так изначально хотел делать, но уперся в тесты на гите которые

2023-04-15 14:04 UTC, mshogin requested changes
Отлично, код стал приятнее и понятнее. Осталось 3 маленьких, но важных момента.

2023-04-15 14:04 UTC, mshogin commented on cmd/agent/main.go
> +	parseFlagsOs()
ошибку необходимо обработать и сделать log.Fatalf если ошибка

2023-04-15 14:04 UTC, mshogin commented on internal/server/handlers/updateHandlers_test.go
> +	testsGauge := []struct {
необходимо либо обьединить testsGauge c testsCounter
либо сделать 2 отдельных теста
```
func TestUpdateCounter
 .....
 
 func TestUpdateGauge
 ```

2023-04-15 14:04 UTC, mshogin commented on internal/server/handlers/valueHandler_test.go
> +func TestValueHandler(t *testing.T) {
необходимо либо обьединить testsGauge c testsCounter
либо сделать 2 отдельных теста

```
func TestValueCounter
 .....
 
 func TestValueGauge
```

2023-04-15 16:04 UTC, mshogin approved these changes
Очень здорово и оперативно поработали. Спасибо за проделанную работу!

2023-05-20 05:53 UTC, merged